### PR TITLE
Use Signals instead of Proxy

### PR DESCRIPTION
**Pull request by wobsoriano**
This PR aims to remove the usage of Solid's `createStore` and use `createSignal` instead. It can improve performance, by not having to pay for reconciliation + proxies. You can still pass a custom equality function that will then be passed to the [equals](https://www.solidjs.com/docs/latest/api#options) option of `createSignal`.

This will be a breaking change, since `useStore` hook will return an accessor now instead of a proxy:

Before

```ts
const state = useStore()
// console.log(state.bears)

const state = useStore(state => state.bears)
// console.log(bears)

const [bears, bulls] = useStore(state => [state.bears, state.bulls], shallow);
// console.log(bears, bulls)
```

After

```ts
const state = useStore()
// console.log(state().bears)

const state = useStore(state => state.bears)
// console.log(bears())

const state = useStore(state => [state.bears, state.bulls], shallow);
const bears = () => state()[0]
const bulls = () => state()[1]
// console.log(bears(), bulls())
```

Fixes https://github.com/wobsoriano/solid-zustand/issues/7

### CODE REVIEW

**Comment by wobsoriano** [comment]
I actually think we can keep the current implementation to not have breaking change, and have a separate `create` function for returning signals:

```ts
// proxy
/**
 * @deprecated Use `import { createWithStore } from 'solid-zustand'` instead.
 */
import create from 'solid-zustand'

// proxy
import { createWithStore } from 'solid-zustand'

// signal
import { createWithSignal } from 'solid-zustand'
```

**Comment by bigmistqke** [comment]
Haven't looked yet at the implementation, but dx is a bit gnarly if you do these type of `(state) => [state.something, ...]` selectors. Reminds me of a similar problem I am having with porting `react-three-fiber`s `useLoader` for `solid-three`.

I realize now my initial proposal was a bit naive, if you did anything more then just returning a selected property inside the selector-callback it wouldn't work. Makes me understand your initial implementation better too.

So offering the both is a sensible idea.

It could be an option to set them with config too maybe. Giving up bit of tree-shaking for flexibility:
```ts
// initialize with default. without config it could default to 'store' for backwards compatibility.
const store = create((set, get) => ..., { as: 'signal' });

const valueAsSignal = store(state => state.key);
const valueAsStore = store(state => state.key, { as: 'store'  });
```

**Comment by XantreGodlike** [comment]
When it will be merged. Idea looks good

**Comment by adamheald13** [comment]
Excited to try this out :)

**Comment by wobsoriano** [comment]
I'm going to merge this in and do updates in main :) tests passed anw

**Pull request merged**
